# Site settings
title:       My Blog :)
description: "junyi's blog"

author: 
  name: zhangjunyi
  email:  zhangjunyiha@gmail.com
  github: https://github.com/junyiha

# Serving
baseurl: ''

# Plugins
plugins:
  - jekyll-paginate
  - rouge

# Pagination
paginate: 10
paginate_path: "home/page:num"

# Outputting
permalink: posts/:title

# Highlight
highlighter: rouge

# Markdown Processors
markdown: kramdown  # [ maruku | rdiscount | kramdown | redcarpet ]
kramdown:
  input: GFM
  syntax_highlighter: rouge # coderay
  syntax_highlighter_opts:
    css_class: highlight
    default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Layout
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Build settings
exclude: 
  - '_posts/notes/PDF'
  - '*.jpeg'
  - '*.jpg'
  - '*.png'
  - '*.pdf'
  - '*.zip'
  - '*.log'
  - '*.docx'
  - '*.mp4'
  - '_posts/notes/Project'
  - '_posts/notes/Personal/2024-05-22-资金.md'